package com.mycompany.myapp;


import com.codename1.components.ImageViewer;
import static com.codename1.ui.CN.*;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.ui.Toolbar;
import java.io.IOException;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.io.NetworkEvent;
import com.codename1.ui.Container;
import com.mycompany.myapp.gui.HomeForm;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class MyApplication {

   private Container c1;
    private ImageViewer img1;
   
       Resources res;
       private Form current;
       public static Resources theme;

    public static Resources getTheme() {
        return theme;
    }
    
    public void init(Object context) {
      
                
        updateNetworkThreadCount(3);
        Resources theme = UIManager.initFirstTheme("/theme");
        Toolbar.setGlobalToolbar(true);
    }

    public void start() {
        if (current != null) {
            current.show();
            return;
        }
          MyApplication.theme = MyApplication.getTheme();
    
        
       new HomeForm().show();
       // new MapForm(current);
        //new ListLivraisonForm();
       //new ActivateForm();
      // new ActivateForm(res);
      //new Email().show();
      
      
    }

    public void stop() {
        current = getCurrentForm();
        if (current instanceof Dialog) {
            ((Dialog) current).dispose();
            current = getCurrentForm();
        }
    }

    public void destroy() {
    }

}